[package]
name = "multithread_window"
version = "0.1.0"
authors = ["Azriel Hoh <azriel91@gmail.com>"]

[dependencies]
gfx = { version = "0.17.1", features = ["serialize"] }
gfx_window_glutin = "0.25"
glutin = "0.17"
